name: Bug report
description: File a bug report for the AG Grid Figma design system
title: "[Bug report]: "
labels: ["Bug report"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - markdurrant
body:
  - type: markdown
    attributes:
      value: |
          Thank you for getting in touch with about the [AG Grid Figma design system](https://ag-grid.com/javascript-data-grid/ag-grid-design-system/)! Please detail your bug report bellow.
          
          If you are an **AG Grid Enterprise** customer you can also request features or file bug reports via [Zendesk](https://ag-grid.zendesk.com/hc/en-us).
  - type: markdown
    attributes:
      value: "<br />" 
  - type: textarea
    id: figma-bug 
    attributes:
      label: Your bug report...
      description: Please add as much detail as possible about the bug you've encountered. 
      placeholder:
      value: |
          To file a bug report please provide the following information...

          - Description of the bug you're experiencing 
          - Clear step by step instructions to reproduce the bug 
          - How has your experience of using the AG Grid Figma design system been? What could we do to improve?

          If possible please attach a screenshot(s) or `.fig` file that can help us quickly understand your bug report. 
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thank you for you feedback. 
