name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      value: |
        We're keen to investigate potential issues you've found with AG Grid.
        
        **Customers of AG Grid Enterprise**
        If you are an AG Grid Enterprise customer please submit any bug reports in our support system instead.
        
        Please provide all the items listed below:
        1. Link to a live sample reproducing the issue. You can build one by modifying any of our documentation examples:
           https://ag-grid.com/javascript-data-grid/
        2. List of steps to reproduce issue with live sample
        3. Description of current behavior
        4. Description of correct behavior
    validations:
      required: true
  - type: dropdown
    id: repro
    attributes:
      label: Reproducible Scenario
      description: Have you supplied a reproducible scenario (e.g. plunker, codesandbox, etc.) in the description above?
      options:
        - "Yes"
        - "No (Will delay finding a solution)"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Which version of our software are you using?
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Which operating system are you using?
      multiple: true
      options:
        - Windows
        - MacOS
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
