name: Request a Feature
description: Request a Feature
title: "[Feature]: "
labels: ["triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your suggestion!
  - type: textarea
    id: what-to-implement
    attributes:
      label: What would you like us to implement?
      description: Be detailed and provide as much information as possible!
      value: |
        **Add an example from our [documentation](https://ag-grid.com/javascript-data-grid/) to show your use case**

        **Describe the current functionality**
        
        **Describe your desired functionality**
    validations:
      required: true
  - type: dropdown
    id: repro
    attributes:
      label: Reproducible Scenario
      description: Have you supplied a reproducible scenario (e.g. plunker, codesandbox, etc.) in the description above?
      options:
        - "Yes"
        - "No (Will delay finding a solution)"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Which version of our software are you using?
    validations:
      required: true
