name: Request a Feature
description: Request a Feature
title: "[Feature]: "
labels: ["FR-proposed"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your suggestion!
  - type: textarea
    id: what-to-implement
    attributes:
      label: What would you like us to implement?
      description: Be detailed and provide as much information as possible!
      value: |
        Example web-based scenario to show your use case
        
        Desired functionality
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Which version of our software are you using?
    validations:
      required: true
