name: Feature Request
description: Request features for the AG Grid Figma design system
title: "[Feature Request]: "
labels: ["Feature Request"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - markdurrant
body:
  - type: markdown
    attributes:
      value: |
          Thank you for getting in touch with about the [AG Grid Figma design system](https://ag-grid.com/javascript-data-grid/ag-grid-design-system/)! Please detail your feature request bellow.
          
          If you are an **AG Grid Enterprise** customer you can also request features or file bug reports via [Zendesk](https://ag-grid.zendesk.com/hc/en-us).
  - type: markdown
    attributes:
      value: "<br />" 
  - type: textarea
    id: figma-feature
    attributes:
      label: Your feature request...
      description: Please add as much detail as possible about the feature you'd like to see in the AG Grid Figma Design System .If possible please attach a screenshot(s) or `.fig` file that can help us quickly understand your feature request.
      placeholder:
      value: |
          Please provide the following information...

          - Description of the new feature 
          - What you hope to achieve with the new feature 
          - Any links to AG Grid documentation detailing the relevant grid features
          - How has your experience of using the AG Grid Figma design system been? What could we do to improve?

          If possible please attach a screenshot(s) or `.fig` file that can help us quickly understand your feature request. 
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thank you for you feedback. 
