name: Figma issue
description: Contact us regarding our Figma Design System
title: "[Figma]: "
labels: ["Figma"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thank you for getting in touch with us!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Have you encountered a bug or are you requesting a feature?
      placeholder:
      value: "A bug happened/I would like X feature"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Which version of our software are you using?
    validations:
      required: true
