name: Support Request
description: Request support from our awesome community!
title: "[Support Request]: "
labels: ["managed-by-community"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: "Please clearly explain what you are trying to achieve - a web-based scenario (plunker, codesandbox, etc.) will make it easier to help."
      value: 
    validations:
      required: true
  - type: dropdown
    id: repro
    attributes:
      label: Reproducible Scenario
      description: Have you supplied a reproducible scenario (e.g. plunker, codesandbox, etc.) in the description above?
      options:
        - "Yes"
        - "No (Will delay finding a solution)"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Which version of our software are you using?
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Which operating system are you using?
      multiple: true
      options:
        - Windows
        - MacOS
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
